"$schema" = 'https://starship.rs/config-schema.json'

palette = "catppuccin_mocha"
format = """
[░▒▓](flamingo)\
$os\
[](bg:blue fg:flamingo)\
$directory\
[](fg:blue bg:mauve)\
$git_branch\
$git_status\
[](fg:mauve bg:surface0)\
$nodejs\
$rust\
$golang\
$dotnet\
$kubernetes\
[](surface0)\
$time\
\n$character"""

[character]
success_symbol = "[ ](fg:sky)"
error_symbol = "[ ](red)"
vicmd_symbol = "[ ](lavender)"

[os]
disabled = false
style = "bg:flamingo fg:crust bold"

[os.symbols]
Windows = "󰍲 "
Ubuntu = "󰕈 "
SUSE = " "
Raspbian = "󰐿 "
Mint = "󰣭 "
Macos = " "
Manjaro = " "
Linux = "󰌽 "
Gentoo = "󰣨 "
Fedora = "󰣛 "
Alpine = " "
Amazon = " "
Android = " "
Arch = "󰣇 "
Artix = "󰣇 "
CentOS = " "
Debian = "󰣚 "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛"

[directory]
style = "fg:base bg:blue"
format = "[ $path ]($style)"
truncation_length = 5
truncation_symbol = "…/"
truncate_to_repo = false

# [directory.substitutions]
# "Documents" = " "
# "Downloads" = " "
# "Music" = " "
# "Pictures" = " "
# "/work" = "/ "

[git_branch]
symbol = ""
style = "bg:mauve"
format = '[[ $symbol $branch ](fg:base bg:mauve)]($style)'

[git_status]
style = "bg:mauve"
format = '[[($ahead_behind)](fg:base bg:mauve)]($style)'
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[nodejs]
symbol = ""
style = "bg:surface0"
format = '[[ $symbol ($version) ](fg:maroon bg:surface0)]($style)'

[rust]
symbol = ""
style = "bg:surface0"
format = '[[ $symbol ($version) ](fg:maroon bg:surface0)]($style)'

[golang]
symbol = "ﳑ"
style = "bg:surface0"
format = '[[ $symbol ($version) ](fg:maroon bg:surface0)]($style)'

[dotnet]
symbol = "󱚣"
style = "bg:surface0"
format = '[[ $symbol ($version) ](fg:pink bg:surface0)]($style)'

[kubernetes]
symbol = "󱃾"
style = "bg:surface0"
format = '[[ $symbol ($version) ](fg:pink bg:surface0)]($style)'

[time]
disabled = false 
time_format = "%R" # Hour:Minute Format
style = "bg:base"
format = '[[  $time ](fg:overlay2 bg:base)]($style)'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

